### ISSUE TITLE
Test #2 fails against sciClone 1.0.7

### ISSUE THREAD

**Issue by armish** [genome/sciclone-meta#1]
Hi there,

Trying out your package and the first thing I would like to do was to replicate your examples with the test data. Looks like test #2 is failing on me, but I am not sure why. Here is the notebook for reference: https://gist.github.com/armish/e4198730ab82e0f53600 

See step 7 for the error message:

```
[1] "checking input data..."
can't do clustering - no copy number 2 regions to operate on in sample 1 
Error in is.data.frame(x): trying to get slot "vafs.merged" from an object of a basic class ("NULL") with no slots
Error in sc.plot1d(sc): trying to get slot "densities" from an object of a basic class ("NULL") with no slots
Error in sc.plot2d(sc): trying to get slot "vafs.merged" from an object of a basic class ("NULL") with no slots
```

Any idea as to why this is happening? Should I be worried about that 1-sample example that seems to run fine but produces a different plot from the one shown in the README, too?

![screen shot 2016-03-15 at 3 46 17 pm](https://cloud.githubusercontent.com/assets/7809/13791775/15757612-eac5-11e5-8949-2fa6175a81c4.png)

**Comment by chrisamiller** [comment]
I'm unable to replicate your issue with a fresh checkout of both sciClone and the test data. Here's what I get when running the shortTests.R file:
https://gist.github.com/chrisamiller/d2be64d0d1ae70b27af6

Are you actually running R within an ipython notebook, or just pasting results there?  If the former, what happens if you run it outside of that environment?  What version of R are you using?  Can you dump your sessionInfo?

**Comment by armish** [comment]
Hey Chris,

Just to make sure: I did clean up everything, start with a clean R installation and install the latest revision from the GitHub - this seems to do the trick. I was able to run it without any problems: https://gist.github.com/armish/31f012635ce6c363c8a4

Having said that, my clustering results still seem a bit different from the ones highlighted in the repo:
![screen shot 2016-03-21 at 11 13 38 am](https://cloud.githubusercontent.com/assets/7809/13923435/fe8fd956-ef56-11e5-9ff6-f2c4d57bef5c.png)
![screen shot 2016-03-21 at 11 13 42 am](https://cloud.githubusercontent.com/assets/7809/13923436/fe9287fa-ef56-11e5-8da5-a7c7a4fdb4cd.png)
![clusters3 3d](https://cloud.githubusercontent.com/assets/7809/13923446/084a6cb8-ef57-11e5-91c5-40e4266cdde1.gif)

For the sake of the argument, here is my `session_info()`:

```
> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
 [1] grid      stats4    parallel  stats     graphics  grDevices utils    
 [8] datasets  methods   base     

other attached packages:
 [1] sciClone_1.1.0       TeachingDemos_2.10   MKmisc_0.991        
 [4] plotrix_3.6-1        RColorBrewer_1.1-2   rgl_0.95.1441       
 [7] bmm_0.3.1            NORMT3_1.0-3         ggplot2_2.1.0       
[10] IRanges_2.4.8        S4Vectors_0.8.11     BiocGenerics_0.16.1 
[13] BiocInstaller_1.20.1 devtools_1.10.0     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3       munsell_0.4.3     colorspace_1.2-6  R6_2.1.2         
 [5] httr_1.1.0        plyr_1.8.3        tools_3.2.4       gtable_0.2.0     
 [9] git2r_0.14.0      withr_1.0.1       digest_0.6.9      curl_0.9.6       
[13] memoise_1.0.0     robustbase_0.92-5 DEoptimR_1.0-4    scales_0.4.0     
```

**Comment by chrisamiller** [comment]
I'm sorry - what specific differences are you seeing? A straight diff of the results/ files will fail because of rounding or because there's no seed set on the RNG. The sorted first 10 cols of each cluster file should match though (cluster assignments should be essentially the same, etc).

**Comment by armish** [comment]
Sorry about not pointing out which plots I meant in my comment. I was assuming that these tests were supposed to generate the following plots (from https://github.com/genome/sciclone#visualization):
![screen shot 2016-03-21 at 11 52 42 am](https://cloud.githubusercontent.com/assets/7809/13924699/ac438544-ef5b-11e5-9d97-9247de0b79de.png)

but looks like I was wrong?

**Comment by chrisamiller** [comment]
Nope - those plots are examples generated from elsewhere. The results/ folder in the sciclone-meta/tests folder has the expected output from the short test.  Be sure to update to the version I pushed last night - it no longer overwrites the results so you can compare the output to the expected output.

**Comment by armish** [comment]
gotcha - thanks!
